# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lokalise2 < Formula
  desc "Lokalise CLI v2"
  homepage "https://github.com/lokalise/lokalise-cli-2-go"
  version "2.6.9"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lokalise/lokalise-cli-2-go/releases/download/v2.6.9/lokalise2_darwin_amd64.tar.gz"
      sha256 "dc429c58fc554234d3c13d2486907a4c1324e78e0aba2902a9acfafca579d516"

      def install
        bin.install "lokalise2"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lokalise/lokalise-cli-2-go/releases/download/v2.6.9/lokalise2_darwin_arm64.tar.gz"
      sha256 "b6d09a7ad9b6be2ad5ea052fca7d71d0944aad588e007286c550c4dbd284d561"

      def install
        bin.install "lokalise2"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lokalise/lokalise-cli-2-go/releases/download/v2.6.9/lokalise2_linux_arm64.tar.gz"
      sha256 "f80f9d38dc8b5c7c9856e6da60941719682648e8ef098dc0ce75f0b193702923"

      def install
        bin.install "lokalise2"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/lokalise/lokalise-cli-2-go/releases/download/v2.6.9/lokalise2_linux_armv6.tar.gz"
      sha256 "cdf4138e34a75e867d43b1e47b4d8d24fbf8083e8d3a55fb31bd0d24f641b708"

      def install
        bin.install "lokalise2"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/lokalise/lokalise-cli-2-go/releases/download/v2.6.9/lokalise2_linux_amd64.tar.gz"
      sha256 "68b254fad463adb011cff98c57fc145606a92c7914312593a97b7a3ff1dc63ab"

      def install
        bin.install "lokalise2"
      end
    end
  end
end
